// Builds js/deals.js: seeds whose deals the solver has proven winnable, verified by replay.
// Usage: node tools/gen-deals.js [draw3Count] [draw1Count]
import { Worker, isMainThread, parentPort, workerData } from 'node:worker_threads';
import { writeFileSync } from 'node:fs';
import { cpus } from 'node:os';
import { deal } from '../js/engine.js';
import { solve, reset } from '../js/solver.js';
import { replay } from './replay.js';

const NODE_LIMIT = 20000;

if (!isMainThread) {
  const { drawCount, start, step, want } = workerData;
  for (let seed = start, found = 0; found < want; seed += step) {
    reset(); // each deal is its own game
    const r = solve(deal(seed, drawCount), NODE_LIMIT);
    if (r.solved && replay(seed, drawCount, r.path)) { parentPort.postMessage(seed); found++; }
  }
} else {
  const want3 = Number(process.argv[2] || 3000), want1 = Number(process.argv[3] || 1000);
  const threads = cpus().length;
  const run = (drawCount, want) => new Promise((resolve) => {
    const seeds = []; let finished = 0;
    const per = Math.ceil(want / threads);
    for (let t = 0; t < threads; t++) {
      const w = new Worker(new URL(import.meta.url), { workerData: { drawCount, start: 1 + t, step: threads, want: per } });
      w.on('message', (s) => { seeds.push(s); if (seeds.length % 250 === 0) console.log(`draw ${drawCount}: ${seeds.length}`); });
      w.on('exit', () => { if (++finished === threads) resolve(seeds.sort((a, b) => a - b).slice(0, want)); });
    }
  });
  const d3 = await run(3, want3);
  const d1 = await run(1, want1);
  writeFileSync(new URL('../js/deals.js', import.meta.url),
    '// Generated by tools/gen-deals.js. Every seed here is a deal the solver has won.\n' +
    `export const DEALS = {\n  3: [${d3.join(',')}],\n  1: [${d1.join(',')}],\n};\n`);
  console.log(`wrote ${d3.length} draw-3 and ${d1.length} draw-1 deals`);
}
